npcs:
  '1': "Джони"
  '2': "Джони2"
  '68': "СК"
  '69': "Travel"
  '71': "Arena"
  '53': "Torn"
  '46': "Tyrn"
  '54': "Hugo"
  '52': "Tafi"
  '55': "Brom"

player_hider:
  empty_hider: #No one can see any players inside a secret room.
    #The source_player argument is left out to match all players.    
    source_player: in_secretRoom

compass:
  compassHolmar:
    name: Волшебный компас
    location: 0;64;0;world
    item: compas
    

holograms:
  beton:
    lines:
    - '&l&4Выход с арены'
    location: -628;79;290;world
    conditions: arena
    check_interval: 20
    # Maximum hologram display distance (optional)
    max_range: 40

  Team:
    lines:
    - '&lВыберите сторону'
    location: -227;75;-66;world

menus:
  questMenu:
    height: 4
    title: "&6&lQuests"
    bind: "openMenuItem"
    command: "/quests"
    slots:
      0-3: "filler,filler,filler,filler"
      4: "reputation"
      5-8: "filler,filler,filler,filler"
      9: "skeletonQuestActive,skeletonQuestDone"
      10: "goldQuestActive,goldQuestDone"
      27-35: "filler,filler,filler,filler,filler,filler,filler,filler,filler"

    items:
      skeletonQuestActive:
        item: "skeletonQuestActiveItem"
        amount: 1
        conditions: "!skeletonQuestDone"
        text:
            - "&7[Quest] &f&lBone ripper"
            - "&f&oRipp some skeletons off"
            - "&f&otheir bones to complete"
            - "&f&othis quest."
            - "&f&o"
            - "&eLeft click to locate NPC."
        click:
          left: "locationNotify"
        close: true
      skeletonQuestDone:
        item: "questDone"
        amount: 1
        conditions: "skeletonQuestDone"
        text:
            - "&2[Quest] &f&lBone ripper"
            - "&f&oRipp some skeletons off"
            - "&f&otheir bones to complete"
            - "&f&othis quest."
            - "&f&o"
            - "&2Quest completed!"
        close: false
      goldQuestActive:
        item: "goldQuestActiveItem"
        amount: 1
        conditions: "!goldQuestDone"
        text:
            - "&7[Quest] &f&lGold rush"
            - "&f&oMine some gold"
            - "&f&oto complete this quest."
        click:
          left: "locationNotify"
        close: true
      goldQuestDone:
        item: "questDone"
        amount: 1
        conditions: "goldQuestDone"
        text:
            - "&2[Quest] &f&lGold rush"
            - "&f&oMine some gold"
            - "&f&oto complete this quest."
            - "&2Quest completed!"
        close: false
      reputation:
        item: "xpBottle" 
        amount: 1
        text:
            - "&2Quest Level: &6&l%point.quest_reputation.amount%"
        close: true
      filler: 
        text: "&a "
        item: "filler"

conditions:
  skeletonQuestDone: "tag skeletonQuestDone"
  goldQuestDone: "tag goldQuestDone"
events:
  locationNotify: "notify &cThe skeletons roam at x\\:123 z\\:456!"
items:
  openMenuItem: "BOOK title:Quests"

  xpBottle: "EXPERIENCE_BOTTLE"
  filler: "GRAY_STAINED_GLASS_PANE"

  skeletonQuestActiveItem: "BONE"
  goldQuestActiveItem: "RAW_GOLD"
  questDone: "LIME_CONCRETE"